package com.xworkz.dream.constants;

public enum SheetConstant {

	COLUMN_SL_NO(0), COLUMN_EMAIL(2), COLUMN_TRANSECTION_ID(4), COLUMN_LAST_FEES_PAID_DATE(3), COLUMN_PAID_AMOUNT(5),
	COLUMN_PAYMENT_MODE(6), COLUMN__FOLLOWUP_STATUS(7), COLUMN_FEES_FOLLOWUP_DATE(8), COLUMN_FOLLOWIUP_CALBACK_DATE(9),
	COLUMN__NAME(1), COLUMN_REMINDER_DATE(10), COLUMN_FEES_CONCESSION(11), COLUMN_FEES_STATUS(12),
	COLUMN_MAIL_SEND_STATUS(13), COLUMN_COMMENTS(14), COLUMN_ADMIN_CREATED_BY(15), COLUMN_ADMIN_CREATED_AT(16),
	COLUMN_ADMIN_UPDATED_BY(17), COLUMN_ADMIN_UPDATED_AT(18), COLUMN_DATA_FLAG(19);

	private int index;

	private SheetConstant(int index) {
		this.index = index;
	}

	public int getIndex() {
		return index;
	}

}
