
sheets:
  credentialsPath: classpath:META-INF/credentials-prod.json
  liveKey: live_a15c297cd6b71c1d8894


mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=
  subject: Thank you for registring at x-workz

 
mail:
   smtpHost: smtp.elasticemail.com
   smtpPort: 2525
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  sheetId: 1HI3nKYRbXNl2cu9rKwqKp3tznOZ7ziOupokU_daFZ8E
  cookieDomain: ombn.in


logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
  file:
    name: ../opt/tomcat1/logs/Dream-Prod-Logs/Dream.log
    max-size: 10MB
    total-size-cap: 10MB

    max-history: '1'
    clean-history-on-start: 'true'
  level:
    root: INFO
    com:
      xworkz:
        dream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log

---


