
sheets:
  credentialsPath: classpath:META-INF/credentials-pre-prod.json
  liveKey: live_a15c297cd6b71c1d8894_


mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: sEYFZ3gEnWWxZ/miOCilnhOflIskXP7649gfc+570Jnn8uLY+v0edOOc3GbV6WRL
  smtpHostChimp: a0j0nB3E5vAsqSFhZDJrFnes+DFtG2s1zg/08rZDCl0=
  subject: Thank you for registring at x-workz

   
login: 
  teamFile: classpath:team.yml
  sheetId: 1BBvpbYuTvqaXQ2ooVItm0MGqB5XMnNgpHc0ZUW4zqLg
  cookieDomain: ombn.in


logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
  file:
    name: ../opt/tomcat1/logs/Dream-Pre-Prod-Logs/Dream-pre-prod.log
    max-size: 10MB
    total-size-cap: 10MB
    max-history: '1'
    clean-history-on-start: 'true'
  level:
    root: INFO
    com:
      xworkz:
        dream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log

---


