
sheets:
  credentialsPath: classpath:META-INF/credentials-pre-prod.json
  liveKey: live_d485f9b87a825393bc2f


mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=

 
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  sheetId: 1BBvpbYuTvqaXQ2ooVItm0MGqB5XMnNgpHc0ZUW4zqLg
  cookieDomain: ombn.in


logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
  file:
    name: ../opt/tomcat1/logs/Dream-Prod-Logs/Dream-pre-prod.log
    max-size: 10MB
    total-size-cap: 10MB

    max-history: '1'
    clean-history-on-start: 'true'
  level:
    root: INFO
    com:
      xworkz:
        dream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log

---


