
sheets:
  range: A3:AC
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  attendanceInfoRange: attendanceInfo!A2:M
  attendanceList: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:M
  credentialsPath: classpath:META-INF/credentials-prod.json


 
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  userFile: classpath:users.yml
  sheetId: 1HI3nKYRbXNl2cu9rKwqKp3tznOZ7ziOupokU_daFZ8E
  cookieDomain: ombn.in
---

