
sheets:
  range: A3:AC
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  attendanceInfoRange: attendanceInfo!A2:M
  attendanceList: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:M
  credentialsPath: classpath:META-INF/credentials-prod.json
  liveKey: live_d485f9b87a825393bc2f


mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=

 
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  sheetId: 1HI3nKYRbXNl2cu9rKwqKp3tznOZ7ziOupokU_daFZ8E
  cookieDomain: ombn.in


logging:
  logback:
    rollingpolicy:
      max-file-size: 0
  file:
    name: ../opt/tomcat1/logs/Dream-Prod-Logs/Dream.log
    max-size: 10MB
    total-size-cap: 10MB

    max-history: '1'
    clean-history-on-start: 'true'
  level:
    root: INFO
    com:
      xworkz:
        dream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log

---


