
sheets:
  range: A3:AH
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  attendanceInfoRange: attendanceInfo!A2:M
  attendanceList: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:M
  credentialsPath: classpath:META-INF/credentials-dev.json
  liveKey: live_d485f9b87a825393bc2i

mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0= 

logging:
  file:
    name: ../Dream.log
    max-size: 1MB
    total-size-cap: 2MB
    max-history: '1'
    clean-history-on-start: 'true'
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log


mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789
    
login: 
  teamFile: classpath:team.yml
  userFile: classpath:users.yml
  sheetId: 1p3G4et36vkzSDs3W63cj6qnUFEWljLos2HHXIZd78Gg
  cookieDomain: ombn.in
---

