spring:
   profiles:
      active: local

   freemarker:
    template-loader-path: classpath:/templates/

sheets:
 
  appName: Dream Api
  range: A3:AC
  emailRange: C3:C
  contactNumberRange: D3:D
  dropdownRange: dropDowns!A2:I
  loginInfoRange: loginInfo!A2:B
  followUpRange: followUp!A2:N
  followUpStatus: followUpStatus!A2:L
  rowStartRange: A
  rowEndRange: AC    
  traineeSheetName: xworkzApi!
  followUpSheetName: followUp!
  followUprowStartRange: A2
  followUprowEndRange: N
  followUpEmailRange: followUp!C2:C
  idRange: xworkzApi!A3:A  
  followUpRowCurrentStartRange: G
  followUpRowCurrentEndRange: H
  emailAndNameRange: xworkzApi!A2:C
  batchDetailsSheetName: batchDetails!
  batchDetailsStartRange: A2
  batchDetailsEndRange: I
  batchDetails: batchDetails!A2:I
  batchDetailsRange: batchDetails!A2:I 
  batchIdRange: batchDetails!A2:A
  dateOfBirthDetailsSheetName: dateOfBirthDetails!
  dateOfBirthDetailsRange: dateOfBirthDetails!A2:E
  birthdayRange: dateOfBirthDetails!A2:A
  attendanceInfoRange: attendanceInfo!A2:M
  attendanceInfoIDRange: attendanceInfo!A2:J
  followUpStatusIdRange: followUpStatus!A2:A
  attendanceInfoByName: attendanceInfo!A2:E
  attendanceList: attendanceList!A2:J
  attendanceListByEmail: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:M
  batchDetailsCourseNameRange: batchDetails!B2:B
  idAttandanceInfoRange: A3:A
  presentRange: H
  absentRange: I
  AttandanceInfoSheetName: attendanceInfo!
  attendanceListDefaultRange: attendanceInfo!J2:j
  attendanceInfoMarkAs:  J

mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=

mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 


    
login:
  userFile: classpath:users.yml
  

server:
  port : 8081

  

---


