spring:
   profiles:
      active: preProd
   freemarker:
    template-loader-path: classpath:/templates/
sheets:
  appName: Dream Api
  range: A3:AH 
  emailRange: C3:C
  contactNumberRange: D3:D
  dropdownRange: dropDowns!A2:I
  loginInfoRange: loginInfo!A2:B 
  followUpRange: followUp!A2:Q 
  followUpStatus: followUpStatus!A2:L
  rowStartRange: B
  rowEndRange: AH 
  traineeSheetName: xworkzApi!  
  followUpSheetName: followUp!
  followUprowStartRange: B2  
  followUprowEndRange: Q
  followUpEmailRange: followUp!C2:C
  idRange: xworkzApi!A3:A    
  followUpRowCurrentStartRange: G
  followUpRowCurrentEndRange: H
  emailAndNameRange: xworkzApi!A3:J
  batchDetailsSheetName: batchDetails!
  batchDetailsStartRange: B
  batchDetailsEndRange: K
  batchDetails: batchDetails!A2:I
  batchDetailsRange: batchDetails!A2:K
  batchIdRange: batchDetails!A2:A 

  dateOfBirthDetailsSheetName: dateOfBirthDetails!
  dateOfBirthDetailsRange: dateOfBirthDetails!A2:G
  birthdayRange: dateOfBirthDetails!A2:A
  birthDayStartRow: B
  birthDayEndRow: G
  birthDayEmailRange: dateOfBirthDetails!B2:B

  followUpStatusIdRange: followUpStatus!A2:A
  batchDetailsCourseNameRange: batchDetails!B2:B
  attendanceInfoRange: attendanceInfo!B2:K
  attendanceInfoIDRange: attendanceInfo!A2:K
  attendanceInfoByName: attendanceInfo!A2:K
  attendanceInfoStartRange : B
  attendanceInfoEndRange : K
  attandanceInfoSheetName: attendanceInfo!
  attandenceNameAndCourseRange : attendanceInfo!A2:D
  batchAttendanceInfoSheetName: batchAttendanceInfo!
  batchAttendanceInfoRange: batchAttendanceInfo!B2:D 
  getBatchAttendanceInfoRange: batchAttendanceInfo!A2:D
  batchAttendanceInfoStartRange: B
  batchAttendanceInfoEndRange: D
  feesRegister: FeesDetiles!B2:X
  getFeesDetiles: FeesDetiles!A2:X
  getFeesDetilesfollowupRange : FeesFollowup!A2:J
  feesEmailRange: FeesDetiles!C2:C
  feesFollowUpEmailRange: FeesFollowup!B2:B
  feesFollowUpUpdateRange: FeesFollowup!B2
  feesUpdateStartRange: FeesDetiles!B
  feesUpdateEndRange: :V
  alternativeNumberRange: xworkzApi!AE3:AE 
  usnNumberRange: xworkzApi!AD3:AD
  uniqueNumberRange: xworkzApi!AF3:AF
  clientInformationRange: clientDetails!B2:O
  clientInformationReadRange: clientDetails!A2:O
  clientStartRow: B
  clientEndRow: O
  clientSheetName: clientDetails!
  clientHrInformationRange: clientHRdetails!B2:K
  clientHrInformationReadRange: clientHRdetails!A2:K
  hrStartRow: B
  hrEndRow: K
  hrSheetName: clientHRdetails!
  hrFollowUpInformationRange: ClientHRFollowUpStatus!B2:I
  hrFollowUpInformationReadRange: ClientHRFollowUpStatus!A2:I
  clientDropDownRange: dropDowns!J2:N
  clientEmailRange: clientDetails!C2:C
  clientContactNumberRange: clientDetails!D2:D
  clientWebsiteRange: clientDetails!E2:E
  clientNameRange: clientDetails!B2:B
  clientHrEmailRange: clientHRdetails!D2:D
  clientHrContactNumberRange: clientHRdetails!E2:E
 
  
mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=
  apiKey: q5s7n+mgA+RWaBxOgO6nHQ==
  SMSusername: SL+xd2DS2FEsed/8nyHejg==
  route: FDOqdLkJyWT+cko+myahVg==
  templateIdEnquiry: 6HKBdaSKQYMlftb4kMWF0VTxBWbD67Do+B0r/IfRpi0=
  sender: Qe3VMrqYDSZt78Y3g87Rew==
  smsType: 9FNdD2Wl6OAroiJUgYK5+Q==
  smsSuccess: sCGjjgUOM6/wvTXAUlLQ62PDqM+G+jmJW8AZLKyacf4=
  templateIdCSRDrive: yZtoKQat7O9npjh2pzI0V20wLmn9iUpR6/J1L+bZ61c=

mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 


login:
  userFile: classpath:users.yml
  teamFile: classpath:team.yml

  

server:
  port : 8081
---


