
sheets:
  range: A3:AC
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  attendanceInfoRange: attendanceInfo!A2:K
  attendanceList: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:K


 
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  userFile: classpath:users.yml
  sheetId: 1p3G4et36vkzSDs3W63cj6qnUFEWljLos2HHXIZd78Gg
  cookieDomain: ombn.in
---

