
sheets:
  range: A3:AC
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  attendanceInfoRange: attendanceInfo!A2:M
  attendanceList: attendanceList!A2:J
  attendanceListRange: attendanceList!A2:M
  credentialsPath: classpath:META-INF/credentials-dev.json
  liveKey: live_d485f9b87a825393bc2f


mailChimp:
  userName: 7FzbzzHIVQSVJVz5r4n/bGa/lhNWJCXUq6oqBxBCTYQ=
  password: +mgZp4MIPWMTkaJ/pwphDw==
  smtpHostChimp: yj/mpkyGHCjMIsVaHCMyxQZ4EBNjg/Ep6CbXhjKA7v0=
  apiKey: q5s7n+mgA+RWaBxOgO6nHQ==
  SMSusername: SL+xd2DS2FEsed/8nyHejg==
  route: FDOqdLkJyWT+cko+myahVg==
  templateIdEnquiry: 6HKBdaSKQYMlftb4kMWF0VTxBWbD67Do+B0r/IfRpi0=
  sender: Qe3VMrqYDSZt78Y3g87Rew==
  smsType: 9FNdD2Wl6OAroiJUgYK5+Q==
  smsSuccess: sCGjjgUOM6/wvTXAUlLQ62PDqM+G+jmJW8AZLKyacf4=
 
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  teamFile: classpath:team.yml
  sheetId: 1p3G4et36vkzSDs3W63cj6qnUFEWljLos2HHXIZd78Gg
  cookieDomain: ombn.in


logging:
  file:
    name: ../opt/tomcat1/logs/Dream-Prod-Logs/Dream.log
    max-size: 1MB
    total-size-cap: 10MB
    max-history: '10'
    clean-history-on-start: 'true'
  level:
    root: INFO
    com:
      xworkz:
        dream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: Dream-%d{yyyy-MM-dd}.%i.log

---


