sheets:
  appName: Dream Api
  credentialsPath: classpath:META-INF/credentials.json
  range: A3:M
  emailRange: B3:B
  contactNumberRange: C3:C
  dropdownRange: dropDowns!A2:E
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789 
    
login: 
  userFile: classpath:users.yml
