spring:
   profiles:
      active: dev

sheets:
  appName: Dream Api
  credentialsPath: classpath:META-INF/credentials.json
  range: A3:N
  emailRange: C3:C
  contactNumberRange: D3:D
  dropdownRange: dropDowns!A2:H
  loginInfoRange: loginInfo!A2:B
  followUpRange: followUp!A2:H
  followUpStatus: followUpStatus!A2:H
  rowStartRange: A
  rowEndRange: M
  traineeSheetName: xworkzApi!
  followUpSheetName: followUp!
  idRange: xworkzApi!A3:A
  followUpRowCurrentStartRange: G
  followUpRowCurrentEndRange: H
  emailAndNameRange: xworkzApi!B3:C
  
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789
logging:
  level:
    root: INFO
    
login:
  userFile: classpath:users.yml
  sheetId: 1p3G4et36vkzSDs3W63cj6qnUFEWljLos2HHXIZd78Gg

---

